apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook

resources:
  - guestbook-deployment.yaml
  - guestbook-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-configmap.yaml
  - ingress.yaml
  - cert-issuer.yaml

images:
  - name: guestbook
    newName: ghcr.io/heg-web/k8s-bfritscher
    newTag: main-5c0a983

commonLabels:
  app: guestbook
  version: v1
