apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        # Root directory for static files
        root /usr/share/nginx/html;
        
        # Serve static files
        location /static/ {
            try_files $uri $uri/ =404;
            # Uncomment the following lines to enable caching if assets are versioned
            # expires 1y;
            # add_header Cache-Control "public, immutable";
            # add_header X-Served-By "nginx-static";
        }
        
        # Health check endpoint
        location = /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Default location - should not be reached due to ingress routing
        location / {
            return 404;
        }
    }
