apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      initContainers:
      - name: static-extractor
        image: guestbook  # This will be updated by Kustomize
        command: ['sh', '-c']
        args:
        - |
          echo "Copying static files from /app/static to /shared"
          mkdir -p /shared
          cp -r /app/static/* /shared/ || echo "No static files found or copy failed"
          ls -la /shared
        volumeMounts:
        - name: static-volume
          mountPath: /shared
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: static-volume
          mountPath: /usr/share/nginx/html/static
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
